/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desighnpotify;

/**
 *
 * @author Darya
 */
public class CellShowJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CellShowJpanel
     */
    public CellShowJpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu = new javax.swing.JPopupMenu();
        imagePanel = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        nameLable = new javax.swing.JLabel();
        lable2 = new javax.swing.JLabel();

        jPopupMenu.setToolTipText("add to playlist");

        setLayout(new java.awt.GridBagLayout());

        imagePanel.setLayout(new java.awt.BorderLayout());

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desighnpotify/image/album.png"))); // NOI18N
        imagePanel.add(image, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 107;
        gridBagConstraints.ipady = 106;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 12, 0, 12);
        add(imagePanel, gridBagConstraints);

        nameLable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nameLable.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        add(nameLable, gridBagConstraints);

        lable2.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 13, 12);
        add(lable2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JLabel lable2;
    private javax.swing.JLabel nameLable;
    // End of variables declaration//GEN-END:variables
}
