/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.*;

/**
 *
 * @author Darya
 */
public class LeftPanel extends javax.swing.JPanel {

    /**
     * Creates new form LeftPanel
     */
    public LeftPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        songsButton = new javax.swing.JButton();
        albumsButton = new javax.swing.JButton();
        playlistButton = new javax.swing.JButton();
        addMusic = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(120, 500));
        setLayout(new java.awt.GridBagLayout());

        songsButton.setBackground(new java.awt.Color(51, 51, 51));
        songsButton.setForeground(new java.awt.Color(255, 255, 255));
        ImageIcon songIcon = new ImageIcon(this.getClass().getResource("images/song.png"));
        songsButton.setIcon(songIcon); // NOI18N
        songsButton.setText("Songs");
        songsButton.setToolTipText("Show songs");
        songsButton.setFocusable(false);
        songsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 12, 0, 0);
        add(songsButton, gridBagConstraints);

        albumsButton.setBackground(new java.awt.Color(51, 51, 51));
        albumsButton.setForeground(new java.awt.Color(255, 255, 255));
        ImageIcon albumIcon = new ImageIcon(this.getClass().getResource("images/album.png"));
        albumsButton.setIcon(albumIcon); // NOI18N
        albumsButton.setText("Albums");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 14, 0, 8);
        add(albumsButton, gridBagConstraints);

        playlistButton.setBackground(new java.awt.Color(51, 51, 51));
        playlistButton.setForeground(new java.awt.Color(255, 255, 255));
        ImageIcon playlistIcon = new ImageIcon(this.getClass().getResource("images/playlist.png"));
        playlistButton.setIcon(playlistIcon); // NOI18N
        playlistButton.setText("Playlists");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 8);
        add(playlistButton, gridBagConstraints);

        addMusic.setBackground(new java.awt.Color(51, 51, 51));
        addMusic.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addMusic.setForeground(new java.awt.Color(255, 255, 255));
        addMusic.setText("+ MUSIC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 23, 0, 0);
        add(addMusic, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+ PLAYLIST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 23, 182, 0);
        add(jButton1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void songsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMusic;
    private javax.swing.JButton albumsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton playlistButton;
    private javax.swing.JButton songsButton;
    // End of variables declaration//GEN-END:variables
}
